# Generated by Django 6.0.1 on 2026-01-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("event", models.CharField(blank=True, max_length=255)),
                ("site", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("round", models.CharField(blank=True, max_length=50)),
                ("white_player", models.CharField(db_index=True, max_length=255)),
                ("black_player", models.CharField(db_index=True, max_length=255)),
                ("result", models.CharField(max_length=10)),
                ("white_elo", models.IntegerField(blank=True, null=True)),
                ("black_elo", models.IntegerField(blank=True, null=True)),
                ("time_control", models.CharField(blank=True, max_length=50)),
                ("termination", models.TextField(blank=True)),
                ("moves", models.TextField()),
                ("source_format", models.CharField(max_length=50)),
                ("raw_headers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event"], name="games_game_event_833326_idx")
                ],
            },
        ),
    ]
