# Generated by Django 6.0.1 on 2026-01-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chess_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="opening_ply",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Opening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fen", models.CharField(db_index=True, max_length=100, unique=True)),
                ("eco_code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("moves", models.CharField(max_length=500)),
                ("ply_count", models.IntegerField()),
                ("source", models.CharField(blank=True, max_length=50)),
                ("is_eco_root", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "opening",
                "indexes": [
                    models.Index(
                        fields=["eco_code"], name="opening_eco_cod_e5185e_idx"
                    ),
                    models.Index(fields=["name"], name="opening_name_f617da_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="opening",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chess_core.opening",
            ),
        ),
    ]
