# Generated by Django 6.0.1 on 2026-01-28 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chess_core", "0004_add_move_count_and_indexes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="move_count",
            new_name="move_count_ply",
        ),
    ]
