# Generated by Django 6.0.1 on 2026-01-28 23:00
"""
Rename tables from games_* prefix to cleaner names.

After renaming the app from 'games' to 'chess_core', we also rename the
database tables to remove the legacy 'games_' prefix.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chess_core", "0005_rename_move_count_to_move_count_ply"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="game",
            table="game",
        ),
        migrations.AlterModelTable(
            name="opening",
            table="opening",
        ),
    ]
