# Generated by Django 6.0.1 on 2026-02-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chess_core", "0006_alter_game_table_alter_opening_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="endgame_fen",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="endgame_move_ply",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
