# Generated by Django 6.0.1 on 2026-01-28 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_opening_ply_opening_game_opening"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="opening_ply",
        ),
    ]
