# Generated by Django 6.0.1 on 2026-01-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_game_opening_ply"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="move_count",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="black_elo",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="white_elo",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
